version: "3"

services:
  murex:
    container_name: murex
    image: lmorg/murex:latest
    build:
      args:
        - VERSION=1.20.3
        - GOOS=linux
        - GOARCH=amd64
      context: .
      dockerfile: ./test/buildserver/build
    volumes:
      - ./test/buildserver/bin:/go/bin:rw
    restart: "no"
