version: 2
jobs:
  build:
    working_directory: /go/src/github.com/lmorg/murex
    docker:
      - image: lmorg/murex:ci
        environment:
          GOPATH: /go
          MUREX_BUILD_FLAGS: --no-colour
    
    steps:
      - run:
          name: Nuke old code
          command: cd .. && rm -rf murex && mkdir murex

      - checkout

      - run:
          name: Build and test murex
          command: test/ci-murex.sh

      - run:
          name: Build and test website
          command: test/ci-website.sh

      - run:
          name: Code Coverage (codecov.io)
          command: bash <(curl -s https://codecov.io/bash)

workflows:
  version: 2
  build-workflow:
    jobs:
      - build
