name: ArchLinux AUR Release

on:
  release:
    types: [published]

  workflow_dispatch:

env:
  GO_VERSION: "1.20"
  PKGBUILD:   ".github/workflows/aur/PKGBUILD"
  SRCINFO:    ".github/workflows/aur/SRCINFO"


jobs:
  build:

    runs-on: ubuntu-latest
 
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Go ${{ ENV.GO_VERSION }}
        uses: actions/setup-go@v4
        with:
          go-version: ${{ ENV.GO_VERSION }}

      - name: Install Murex
        run: |
          go build -v github.com/lmorg/murex

      - name: Update PKGBUILD and SRCINFO
        run: |
          export MUREX_VERSION=$(./murex -c "version --no-app-name")
          export PKG_RELEASE="${{ github.run_number }}"
          wget -O - https://github.com/lmorg/murex/archive/refs/tags/v${MUREX_VERSION}.tar.gz > murex.tar.gz
          sha256sum murex.tar.gz | awk '{ print $1 }' > chksum
          export CHECKSUM=$(cat chksum)

          sed -i "s/xxxMUREX_VERSIONxxx/$MUREX_VERSION/" ${{ ENV.PKGBUILD }}
          sed -i "s/xxxPKG_RELEASExxx/$PKG_RELEASE/"     ${{ ENV.PKGBUILD }}
          sed -i "s/xxxCHECKSUMxxx/$CHECKSUM/"           ${{ ENV.PKGBUILD }}
          printf "# ${{ ENV.PKGBUILD }}:\n\n"
          cat ${{ ENV.PKGBUILD }}

          sed -i "s/xxxMUREX_VERSIONxxx/$MUREX_VERSION/" ${{ ENV.SRCINFO }}
          sed -i "s/xxxPKG_RELEASExxx/$PKG_RELEASE/"     ${{ ENV.SRCINFO }}
          sed -i "s/xxxCHECKSUMxxx/$CHECKSUM/"           ${{ ENV.SRCINFO }}
          printf "\n\n# ${{ ENV.SRCINFO }}:\n\n"
          cat ${{ ENV.SRCINFO }}

      - name: Clone AUR, Murex
        run: |
          git clone ssh://aur@aur.archlinux.org/murex.git aur-murex

      - name: Update repo
        run: |
          cp -v ${{ ENV.PKGBUILD }} aur-murex/PKGBUILD
          cp -v ${{ ENV.SRCINFO }}  aur-murex/.SRCINFO
          cd aur-murex
          git commit -am "$(./murex -c "version --no-app-name"), ${{ github.run_number }}"
          

